# macOS
.DS_Store
.AppleDouble
.LSOverride

# VS Code
.vscode/

# Unity generated IDE files
*.csproj
*.sln
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# JetBrains / Rider
.idea/

# Visual Studio cache
.vs/